import fs from 'fs';

const filePath = 'app/src/main/java/com/example/AdvisorEngine.kt';
let text = fs.readFileSync(filePath, 'utf8');

text = text.replace(/ОЛЛ-ИН: превосходное EV/g, "ALL-IN: excellent EV")
           .replace(/Рейз: сильное велью-эквити/g, "Raise: strong value equity")
           .replace(/Колл: эквити/g, "Call: equity")
           .replace(/шансы/g, "odds")
           .replace(/с учетом маржи/g, "with margin")
           .replace(/Рейз \(полублеф\): сильная математическая структура, эквити/g, "Raise (semi-bluff): equity")
           .replace(/Колл \(оборона\): высокая играбельность карт, эквити/g, "Call (defense): equity")
           .replace(/Фолд: математически невыгодно, эквити/g, "Fold: weak equity")
           .replace(/ОЛЛ-ИН: математический превосходный пуш, эквити/g, "ALL-IN: excellent push, equity")
           .replace(/Рейз: велью-агрессия, эквити/g, "Raise: value aggression, equity")
           .replace(/Ставка: получено математическое преимущество, эквити/g, "Bet: math advantage, equity")
           .replace(/Ставка \(блеф\): защита структуры, эквити/g, "Bet (bluff): equity")
           .replace(/Чек: ведение банка по шансам, эквити/g, "Check: pot control, equity")
           .replace(/СрВыч=/g, "Avg=")
           .replace(/L2 ОЛЛ-ИН: защита укороченного стека/g, "L2 ALL-IN: short stack def")
           .replace(/L2 Рейз \(велью-напор\): эксплойт полей, сила/g, "L2 Raise (value): exploit field, power")
           .replace(/L2 Колл: сила/g, "L2 Call: power")
           .replace(/L2 Колл \(оборона\): сильная позиционная дожидаемость/g, "L2 Call (defense): strong pos draw")
           .replace(/L2 Фолд: невыгодно, сила/g, "L2 Fold: weak power")
           .replace(/L2 Рейз \(атака\): инициатива, сила/g, "L2 Raise (attack): initiative, power")
           .replace(/L2 Ставка: велью-линия, сила/g, "L2 Bet: value line, power")
           .replace(/КПФ/g, "Focus")
           .replace(/L2 Чек \(контроль\): ведение пота, сила/g, "L2 Check: pot control, power")
           .replace(/L2 Чек: пас линии, сила/g, "L2 Check: passive line, power")
           .replace(/Калиб=/g, "Calib=")
           .replace(/Неизвестный Пул/g, "Unknown Pool")
           .replace(/авто-защита блайндов/g, "auto blind def")
           .replace(/Оверфолд на/g, "Overfold to")
           .replace(/Авто-блеф/g, "Auto-bluff")
           .replace(/Опп - телефон \(респект\)/g, "Opp is station (respect)")
           .replace(/Респект агрессии Скале!/g, "Respect rock agro!")
           .replace(/Флоат против шир/g, "Float vs wide")
           .replace(/Агрессивный Чек-Рейз!/g, "Agro Check-Raise!")
           .replace(/Блеф/g, "Bluff")
           .replace(/Велью/g, "Value")
           .replace(/Максимизация/g, "Max")
           .replace(/Аккуратный контроль банка \(чек сильного спектра\)/g, "Pot control (check strong range)")
           .replace(/Извлечение велью из сильной спектральной структуры/g, "Value extract")
           .replace(/Пассив/g, "Passive")
           .replace(/Имитация слабости \/ Сбалансированный чек/g, "Fake weak / Bal. check")
           .replace(/Сбор блефов прокаткой/g, "Catch bluffs")
           .replace(/ОЛЛ-ИН по короткому стеку префлоп/g, "ALL-IN short stack preflop")
           .replace(/Пас укороченного стека префлоп/g, "Fold short stack preflop")
           .replace(/Ошибка короткого стека префлоп/g, "Short stack preflop error")
           .replace(/Давление EV максимизировано. Дожим \(ОЛЛ-ИН\) с сильной комбинацией!/g, "Max EV pressure. ALL-IN strong combo!")
           .replace(/Мощный велью! Увеличиваем банк максимизированной ставкой./g, "Strong value! Max bet.")
           .replace(/Смесь/g, "Mix")
           .replace(/Чек=/g, "Check=")
           .replace(/Акт=/g, "Act=")
           .replace(/Агр=/g, "Agr=")
           .replace(/Адаптивное решение/g, "Adaptive decision");

fs.writeFileSync(filePath, text, 'utf8');
